# site_name: CSCS Documentation
# site_description: Documentation for CSCS - Custom Scripting in C#

# theme:
#   name: material
#   features:
#     - navigation.tabs
#     - navigation.sections
#     - toc.integrate
#     - navigation.top
#     - search.suggest
#     - search.highlight

# repo_url: https://github.com/AurasoftEnzo/cscs-docs
# repo_name: AurasoftEnzo/cscs-docs

# nav:
#   - Home: index.md
#   - Getting Started: getting-started.md
#   - Language Basics: language-basics.md

site_name: CSCS Documentation
site_description: Documentation for CSCS - Custom Scripting in C#

theme:
  name: material
  palette:
    - scheme: default
      primary: teal
      accent: purple
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.copy # adds a copy button to code blocks
    # - toc.integrate
    # - navigation.top

nav:
  - Home: index.md
  
  - Getting Started:
    - Installation: getting-started/installation.md
    - First Script: getting-started/first-script.md
  
  - Reference:
    - Variables: reference/variables.md
    - Functions: reference/functions.md
    - Control Flow: reference/control-flow.md

  - API Reference: api-reference.md
  - Examples: examples.md